services:
  jenkins:
    build: .
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - selenoid
    networks:
      - test-network

  selenoid:
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
    volumes:
      - ./selenoid/config:/etc/selenoid/
      - /var/run/docker.sock:/var/run/docker.sock
      - selenoid_videos:/opt/selenoid/video
      - selenoid_logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    networks:
      - test-network

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8082:8080"
    links:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]
    networks:
      - test-network

volumes:
  jenkins_home:
  selenoid_videos:
  selenoid_logs:

networks:
  test-network:
    driver: bridge
